name: 'Github Action: Push To Github'
description: 'Push local changes to GitHub repository'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
