name: "Manual/Auto: delete test"
on:
  push:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Type in input'

jobs:
  test:
    runs-on: ubuntu-18.04
    environment: 
      name: stage
    steps:
      - name: Echo variables
        id: echo-vars
        shell: bash
        run: |
          echo "github.event.inputs.branch-name:" ${{ github.event.inputs.branch-name }}
          echo "github.event.ref:" ${{ github.event.ref }}
          echo "GITHUB_REF:" $GITHUB_REF
          echo "GITHUB_HEAD_REF:" $GITHUB_HEAD_REF
          echo "GITHUB_REF#refs/heads/": ${GITHUB_REF#refs/heads/}
          echo ${{ github.repository }}
          ENVIRONMENTS=$(curl --request GET --url https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/environments --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json')
          REVIEW_PROTECTION=`echo ${ENVIRONMENTS} | jq -r '.environments[]? | select(.name == "staging") | .protection_rules[]? | select(.type == "required_reviewers")`
          
          echo $REVIEW_PROTECTION
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
