name: "Manual/Auto: pull_request test"
on:
  pull_request:
  types: [closed]
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Type in input'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout local actions
        uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2
      - name: Echo variables
        id: echo-vars
        shell: bash
        run: |
          echo "github.event.inputs.branch-name:" ${{ github.event.inputs.branch-name }}
          echo "github.event.ref:" ${{ github.event.ref }}
          echo "GITHUB_REF:" $GITHUB_REF
          echo "GITHUB_HEAD_REF:" $GITHUB_HEAD_REF
          echo "GITHUB_REF#refs/heads/": ${GITHUB_REF#refs/heads/}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
