name: "Manual/Auto: push test"
on:
  push:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Type in input'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo variables
        id: echo-vars
        shell: bash
        run: |
          echo "github.event.inputs.branch-name:" ${{ github.event.inputs.branch-name }}
          echo "github.event.ref:" ${{ github.event.ref }}
          echo "$GITHUB_REF:" $GITHUB_REF
          echo "$GITHUB_HEAD_REF:" $GITHUB_HEAD_REF
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
