# This is a basic workflow that is manually triggered

name: Shell test manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      brand:
          description: 'Type brand(s): adidas and/or nike?'
          required: true

jobs:
  shell-test:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    outputs:
      job_status: ${{ job.status }}
    steps:
      - name: Checkout local actions
        uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2
      - name: Get env URLs
        id: get-env-urls
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.brand }}" == *"adidas"* ]] && [[ "${{ github.event.inputs.brand-name }}" == *"nike"* ]]
          then
              ENV_URLS="sg"
          elif [[ ${{ github.event.inputs.brand }} == *"adidas"* ]]
          then
              ENV_URLS="sg2"
          elif [[ ${{ github.event.inputs.brand }} == *"nike"* ]]
          then
              ENV_URLS="sg3"
          fi
          echo "::set-output name=env-urls::$ENV_URLS"
      - name: test the output
        run: |
          echo ${{ steps.get-env-urls.outputs.env-urls }}
